// <auto-generated />
using AS_FINAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AS_FINAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230621215543_InitialMigrationsAdd")]
    partial class InitialMigrationsAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("LivroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("autores", (string)null);
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("isbn");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("livros", (string)null);
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Autor", b =>
                {
                    b.HasOne("AS_FINAL.Domain.Entities.Livro", "Livro")
                        .WithMany("Autores")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Autores");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Livro", b =>
                {
                    b.HasOne("AS_FINAL.Domain.Entities.Usuario", "Usuario")
                        .WithMany("LivrosEmprestados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Empresta_Livros");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Livro", b =>
                {
                    b.Navigation("Autores");
                });

            modelBuilder.Entity("AS_FINAL.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("LivrosEmprestados");
                });
#pragma warning restore 612, 618
        }
    }
}
